# Enterprise-grade pre-commit configuration for the KrishiSahayak project.
# This pipeline enforces formatting, linting, type safety, and security checks
# automatically before each commit.

repos:
  # === Code Formatter ===
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        args: ["--target-version=py311"]

  # === Linter ===
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]

  # === Static Type Checker ===
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.9.0
    hooks:
      - id: mypy
        files: ^src/

  # === Generic File & Syntax Checks ===
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-merge-conflict
      - id: check-added-large-files
      - id: debug-statements

  # === Documentation Checks ===
  - repo: local
    hooks:
      - id: check-docs
        name: Check Documentation References
        # REFACTORED: A single, clean call to the enhanced script.
        # Easily scalable by adding more .md file paths here.
        entry: python scripts/doc_ref_checker.py --doc docs/ARCHITECTURE.md docs/README.md --ignore-symbols black,isort
        language: system
        types: [markdown]
        pass_filenames: false
        always_run: true
        verbose: true
        description: 'Checks that all file and symbol references in documentation are valid.'

  # === Security Checks ===
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        args: ['--baseline', '.secrets.baseline']