# =============================================================================
# KrishiSahayak Project - Canonical Docker Compose for Local Development
# =============================================================================
# This single file provides an isolated, reproducible development environment
# with live code reloading for the FastAPI service.

version: '3.8'

services:
  dev-server:
    build:
      context: .
      # Assumes a Dockerfile in the root directory for the development environment.
      dockerfile: Dockerfile 
    container_name: krishi_sahayak_dev_server
    restart: unless-stopped
    ports:
      - "8000:8000"
    
    # Mounts local source code into the container for live reloading.
    # Changes made on the host machine will be reflected immediately.
    volumes:
      - ./src:/home/appuser/app/src
      - ./configs:/home/appuser/app/configs
      
    # Load environment variables from a .env file for easy configuration.
    env_file:
      - .env

    environment:
      - PYTHONPATH=/home/appuser/app
      - PYTHONUNBUFFERED=1
      - ENVIRONMENT=development

    # Command to run the Uvicorn development server with live reload enabled.
    command: >
      sh -c "uvicorn krishi_sahayak.api.main:app 
             --host 0.0.0.0 
             --port 8000 
             --reload 
             --reload-dir /home/appuser/app/src"

    # --- Optional GPU Configuration ---
    # Uncomment the following lines if you have an NVIDIA GPU and have set up
    # the NVIDIA Container Toolkit.
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]