version: '3.8'
services:
  api_dev:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    volumes:
      # Mount source code for live reloading
      - ./src:/home/appuser/app/src
      # Mount models and configs so they can be changed without rebuilding
      - ./models:/home/appuser/app/models
      - ./configs:/home/appuser/app/configs
    env_file:
      - .env
    environment:
      - ENVIRONMENT=development
    command: >
      uvicorn src.krishi_sahayak.api.main:app
      --host 0.0.0.0 --port 8000 --reload --reload-dir /home/appuser/app/src
