# configs/master_config.yaml
# ... (project_name, seed, paths sections are unchanged) ...

# Training pipelines
training_pipelines:

  # --- Job 1: Standard RGB Classification ---
  rgb_classification_resnet18:
    type: "classification"
    description: "Train a standard ResNet18 on the merged dataset."
    experiment_name: "rgb_resnet18_on_merged"
    run_test_after_fit: true

    data_loader_params: { num_workers: 4, pin_memory: true }
    data_params:
      metadata_filename: "merged_metadata.csv"
      class_weights_filename: "class_weights.json"

    # REFACTORED: The key is now `architecture_config` instead of `model_config`.
    architecture_config:
      backbone_name: "resnet18"
      pretrained: true
      streams:
        rgb: { channels: 3 }

    training_params:
      batch_size: 64 # Note: batch_size logically belongs here or in data_params
      optimizer: "AdamW"
      learning_rate: 0.001
      weight_decay: 1e-4
    
    trainer_config:
      max_epochs: 50
      precision: "16-mixed"
    
    callbacks:
      early_stopping: { monitor: "val/loss", patience: 10, mode: "min" }
      model_checkpoint: { monitor: "val/loss", save_top_k: 3, mode: "min" }
